# Generated by Django 5.1.1 on 2024-10-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_bio_user_dob_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_alert_notifications',
            field=models.BooleanField(default=True),
        ),
    ]
