# Generated by Django 5.1.1 on 2024-10-10 01:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='disaster',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Resolved', 'Resolved')], default='Ongoing', max_length=20),
        ),
        migrations.AddField(
            model_name='disaster',
            name='type',
            field=models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Fire', 'Fire'), ('Storm', 'Storm')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='disaster_reports/'),
        ),
    ]
