# Generated by Django 5.1.1 on 2024-10-10 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster_management', '0002_disaster_date_disaster_status_disaster_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disaster',
            name='description',
        ),
    ]
